blog/urls.py
from django.urls import path
from .views import (
    PostListView,
    PostDetailView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView,
    UserPostListView,
)
from . import views

urlpatterns = [
    path('index/', views.index, name = 'index'),
    path('', PostListView.as_view(), name = 'blog-home'),
    path('user/<str:username>', UserPostListView.as_view(), name = 'user-posts'),
    path('post/<int:pk>/', PostDetailView.as_view(), name = 'post-detail'), #url pattern with variable
    path('post/new/', PostCreateView.as_view(), name = 'post-create'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name = 'post-update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name = 'post-delete'),
    path('about/', views.about, name = 'blog-about'),
    path('newsfeed/', views.newsfeed, name = 'blog-newsfeed'),
]

#blog/post_list.html
#<app>/<model>_<viewtype>.html

groups/urls.py
from django.urls import path
from . import views

app_name = 'groups'

urlpatterns = [
    path('', views.ListGroups.as_view(), name="all"),
    path("new/", views.CreateGroup.as_view(), name="create"),
    path("posts/in/<slug>/",views.SingleGroup.as_view(),name="single"),
    path("join/<slug>/",views.JoinGroup.as_view(),name="join"),
    path("leave/<slug>/",views.LeaveGroup.as_view(),name="leave"),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from users import views as user_views

from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('', include('users.urls')),
    path('groups/',include("groups.urls", namespace="groups")),
    path('posts/', include("posts.urls", namespace="posts")),

    path('register/', user_views.register, name = "register"),
    path('profile/', user_views.profile, name = "profile"),
    path('editprofile/', user_views.editprofile, name = "editprofile"),
    #path('members/', user_views.members, name = "members"),
    path('login/', auth_views.LoginView.as_view(template_name = 'users/login.html'), name = "login"),
    path('logout/', auth_views.LogoutView.as_view(template_name = 'users/logout.html'), name = "logout"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

groups/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
from django.utils.text import slugify
# from accounts.models import User


from django.contrib.auth.models import User

# https://docs.djangoproject.com/en/2.0/howto/custom-template-tags/#inclusion-tags
# This is for the in_group_members check template tag
from django import template
register = template.Library()


class Group(models.Model):
    name = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(allow_unicode=True, unique=True)
    description = models.TextField(blank=True, default='')
    description_html = models.TextField(editable=False, default='', blank=True)
    members = models.ManyToManyField(User,through="GroupMember")

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        #self.description_html = misaka.html(self.description)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("groups:single", kwargs={"slug": self.slug})


    class Meta:
        ordering = ["name"]


class GroupMember(models.Model):
    group = models.ForeignKey(Group,related_name='memberships',on_delete=models.CASCADE)
    user = models.ForeignKey(User,related_name='user_groups',on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

    class Meta:
        unique_together = ("group", "user")

groups/views.py
from django.contrib import messages
from django.contrib.auth.mixins import(
    LoginRequiredMixin,
    PermissionRequiredMixin
)
from django.urls import reverse
from django.db import IntegrityError
from django.shortcuts import get_object_or_404
from django.views import generic
from groups.models import Group,GroupMember
from . import models

class CreateGroup(LoginRequiredMixin, generic.CreateView):
    fields = ("name", "description")
    model = Group


class SingleGroup(LoginRequiredMixin, generic.DetailView):
    model = Group

class ListGroups(LoginRequiredMixin, generic.ListView):
    model = Group
    ordering = ['name']


class JoinGroup(LoginRequiredMixin, generic.RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse("groups:single",kwargs={"slug": self.kwargs.get("slug")})

    def get(self, request, *args, **kwargs):
        group = get_object_or_404(Group,slug=self.kwargs.get("slug"))

        try:
            GroupMember.objects.create(user=self.request.user,group=group)

        except IntegrityError:
            messages.warning(self.request,("Warning, already a member of {}".format(group.name)))

        else:
            messages.success(self.request,"You are now a member of the {} group.".format(group.name))

        return super().get(request, *args, **kwargs)


class LeaveGroup(LoginRequiredMixin, generic.RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse("groups:single",kwargs={"slug": self.kwargs.get("slug")})

    def get(self, request, *args, **kwargs):
        try:
            membership = models.GroupMember.objects.filter(
                user=self.request.user,
                group__slug=self.kwargs.get("slug")
            ).get()

        except models.GroupMember.DoesNotExist:
            messages.warning(
                self.request,
                "You can't leave this group because you aren't in it."
            )

        else:
            membership.delete()
            messages.success(
                self.request,
                "You have successfully left this group."
            )
        return super().get(request, *args, **kwargs)

groups/templates/groups/group_base.html
{% extends "blog/base.html" %}
{% block content %}

<div class="container">
  <div class="row">
    {% block pregroup %}{% endblock %}
    {% block group_content %}{% endblock %}
    {% block postgroup %}{% endblock %}
  </div>
</div>

{% endblock %}

{% block side_content %}
  {% block group_side %}{% endblock %}
{% endblock %}

groups/templates/groups/group_detail.html
{% extends "groups/group_base.html" %}

{% block group_content %}
<div class="container col-md-10">
	<legend class="border-bottom mb-4">Group Posts: </legend>
	<div class="container">
		{% if user in group.members.all %}
		<div class="container text-center">
			<a href="{% url 'posts:create' %}" class="btn btn-info" role="button"><span class="fa fa-plus"></span>New Post</a>
		</div>
		{% endif %}
		{% if group.posts.count == 0 %}
		<h2>No posts in this group yet!</h2>

		{% else %}
	    {% for post in group.posts.all %}
	      {% include "posts/_post.html" %}
	    {% endfor %}
		{% endif %}
	</div>
</div>
{% endblock %}

{% block group_side %}
<div class="container">

  <legend class="border-bottom mb-4">Group Details: </legend>
  <div class="row">
  <div class="col">
		<h5 class="text-info"> {{group.name}}</h5>
		<small>{{ group.description }}</small>
  </div>
  <div class="<col span="4">
    <div class="content">
    	{% if user in group.members.all %}
				<div class="container">
    		<a href="{% url 'groups:leave' slug=group.slug %}" class="btn btn-danger"><span class="fa fa-times-circle-o"></span>Leave</a>
				</div>
    	{% else %}
    		<a href="{% url 'groups:join' slug=group.slug %}" class="btn btn-success"><span class="fa fa-check-circle-o"></span>Join</a>
    	{% endif %}
    </div>
  </div>
</div>
</div>

  <legend class="border-bottom mb-4">Group Members({{group.members.count}}): </legend>
  <div class="container">
  	<div class="list-group">
      {% for p in group.members.all %}

  		<a href="{% url 'user-detail' p.profile.id %}"
  		class="list-group-item list-group-item-action flex-column align-items-start">
  			<img src="{{ p.profile.image.url }}" height="33px">
        {{ p.username }}
  		</a>

  	{% endfor %}
  </div>
  </div>
{% endblock %}

groups/templates/groups/group_form.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container col-md-10">
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Create Group</legend>
                {{ form | crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Create</button>
            </div>
        </form>
    </div>
  </div>
{% endblock content %}

groups/templates/groups/group_list.html
{% extends "groups/group_base.html" %}


{% block pregroup %}
<div class="container col-md-5 ">
	{% if user.is_authenticated %}
	<a href="{% url 'groups:create' %}" class="btn btn-primary" role="button"><span class="fa fa-plus"></span> Create New Group</a>
	<a href="{% url 'posts:create' %}" class="btn btn-info" role="button"><span class="fa fa-plus"></span> New Group Post</a>
	{% endif %}
</div>
{% endblock %}

{% block group_content %}
<div class="container col-md-10" style = "margin-top: 4rem; margin-bottom: 10rem;">
<div class="col-md-12">
	<div class="list-group">
		{% for group in object_list %}
		<a href="{% url 'groups:single' slug=group.slug %}"
		class="list-group-item list-group-item-action flex-column align-items-start">
			<h3 class="mb-1">{{ group.name }}</h3>
			<p class="mb-1">{{ group.description_html|safe }}</p>
			<div class="d-flex w-40 justify-content-between">
				<small class="text-muted"><span class="badge badge-secondary">
					{{ group.members.count }}</span> member{{ group.members.count|pluralize }}</small>
				<small class="text-muted"><span class="badge badge-secondary">
					{{ group.posts.count }}</span> post{{ group.posts.count|pluralize }}</small>
			<span></span><span></span>
			</div>
		</a>

		{% endfor %}
	</div>
</div>
</div>
{% endblock %}


{% block group_side %}
<div class="container col-md-10">
  <div class="content-section">
    <h3 class="text-center text-info">Your Groups</h3>
      <ul class="list-group">
				{% for group in object_list %}
					{% if user in group.members.all %}
					<a href="{% url 'groups:single' slug=group.slug %}" class="list-group-item list-group-item-action flex-column bg-secondary align-items-start text-center">
	          <b class="mb-0 text-light">{{ group.name }}</b></a>
					{% endif %}
				{% endfor %}
				<br>
		</div>
</div>
{% endblock %}