blog/urls.py
from django.urls import path
from .views import (
    PostListView,
    PostDetailView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView,
    UserPostListView,
)
from . import views

urlpatterns = [
    path('index/', views.index, name = 'index'),
    path('', PostListView.as_view(), name = 'blog-home'),
    path('user/<str:username>', UserPostListView.as_view(), name = 'user-posts'),
    path('post/<int:pk>/', PostDetailView.as_view(), name = 'post-detail'), #url pattern with variable
    path('post/new/', PostCreateView.as_view(), name = 'post-create'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name = 'post-update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name = 'post-delete'),
    path('about/', views.about, name = 'blog-about'),
    path('newsfeed/', views.newsfeed, name = 'blog-newsfeed'),
]

#blog/post_list.html
#<app>/<model>_<viewtype>.html

posts/urls.py
from django.urls import path
from . import views

app_name='posts'

urlpatterns = [
    path('', views.PostList.as_view(), name="all"),
    path("new/", views.CreatePost.as_view(), name="create"),
    path("by/<username>/",views.UserPosts.as_view(),name="for_user"),
    path("by/<username>/<int:pk>/",views.PostDetail.as_view(),name="single"),
    path("delete/<int:pk>/",views.DeletePost.as_view(),name="delete"),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from users import views as user_views

from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('', include('users.urls')),
    path('groups/',include("groups.urls", namespace="groups")),
    path('posts/', include("posts.urls", namespace="posts")),

    path('register/', user_views.register, name = "register"),
    path('profile/', user_views.profile, name = "profile"),
    path('editprofile/', user_views.editprofile, name = "editprofile"),
    #path('members/', user_views.members, name = "members"),
    path('login/', auth_views.LoginView.as_view(template_name = 'users/login.html'), name = "login"),
    path('logout/', auth_views.LogoutView.as_view(template_name = 'users/logout.html'), name = "logout"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length = 100)
    content = models.TextField()
    date_posted = models.DateTimeField(default=timezone.now)
    date_updated = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User,related_name="post", on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post-detail', kwargs={'pk': self.pk})

posts/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse

# pip install misaka
#import misaka

from groups.models import Group

from django.contrib.auth import get_user_model
User = get_user_model()


class Post(models.Model):
    user = models.ForeignKey(User, related_name="posts",on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now=True)
    message = models.TextField()
    message_html = models.TextField(editable=False)
    group = models.ForeignKey(Group, related_name="posts",null=True, blank=True,on_delete=models.CASCADE)

    def __str__(self):
        return self.message

    def save(self, *args, **kwargs):
        #self.message_html = misaka.html(self.message)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse(
            "posts:single",
            kwargs={
                "username": self.user.username,
                "pk": self.pk
            }
        )

    class Meta:
        ordering = ["-created_at"]
        unique_together = ["user", "message"]

posts/forms.py
from django import forms
from . import models
from groups.models import Group, GroupMember
from django.contrib.auth.models import User


class PostForm(forms.ModelForm):
    class Meta:
        fields = ("group", "message")
        model = models.Post

    def clean(self):
        cleaned_data = super().clean()
        grp_name = cleaned_data.get('group')

        if Group.objects.filter(members = User).count() == 0:
            raise forms.ValidationError("You are not in this group")

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib import messages
from django.contrib.auth.models import User
from django.utils import timezone
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView
)
from . models import Post
from groups.models import Group
from users.models import Student

def index(request):
    context = {
        'posts' : Post.objects.all(),
        'groups' : Group.objects.all(),
        'title' : 'Index',
    }
    return render(request, 'blog/index.html', context)

class PostListView(LoginRequiredMixin, ListView):
    model = Post
    template_name = 'blog/home.html'
    #<app>/<model>_<viewtype>.html
    context_object_name = 'posts' #use post.author instead of object.author
    ordering = ['-date_updated'] #for ordering accoing to date
    paginate_by = 10 #buit in paginator function

class UserPostListView(LoginRequiredMixin, ListView):
    model = Post
    template_name = 'blog/user_posts.html'
    context_object_name = 'posts'
    paginate_by = 10

    def get_queryset(self):
        user = get_object_or_404(User, username = self.kwargs.get('username'))
        return Post.objects.filter(author = user).order_by('-date_updated')



class PostDetailView(LoginRequiredMixin, DetailView):
    model = Post

class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    success_url = '/'
    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author or self.request.user.is_staff:
            return True
        return False
    def delete(self, *args, **kwargs):
        messages.success(self.request, "Post Deleted from database")
        return super().delete(*args, **kwargs)


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['title', 'content'] #form fields

    def form_valid(self, form):
        #form<this form> <set author> = current logged in user
        form.instance.author = self.request.user
        #run overridden form_valid method
        return super().form_valid(form)

class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    fields = ['title', 'content'] #form fields

    def form_valid(self, form):
        #form<this form> <set author> = current logged in user
        #form.instance.author = self.request.user
        #run overridden form_valid method
        form.instance.date_updated = timezone.now()
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author or self.request.user.is_staff:
            return True
        return False

    def update(self, *args, **kwargs):
        messages.success(self.request, "Post Updated!")
        return super().update(*args, **kwargs)



def about(request):
    context = {
        'title' : 'About',
    }
    return render(request, 'blog/about.html', context)

def newsfeed(request):
    num = Student.objects.filter(email = "faruqui").count()
    context = {
        'posts' : Post.objects.all(),
        'num' : num,
        'students' : Student.objects.all(),
        #'posts' : Post.objects.filter(author = {{ user }}),
        'title' : 'Newsfeed',
    }
    return render(request, 'blog/newsfeed.html', context)

posts/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.urls import reverse_lazy
from django.http import Http404
from django.views import generic

# pip install django-braces
from braces.views import SelectRelatedMixin

from . import forms
from . import models

from django.contrib.auth import get_user_model
User = get_user_model()


class PostList(LoginRequiredMixin, SelectRelatedMixin, generic.ListView):
    model = models.Post
    select_related = ("user", "group")
    paginate_by = 10


class UserPosts(LoginRequiredMixin, generic.ListView):
    model = models.Post
    template_name = "posts/user_post_list.html"
    paginate_by = 10

    def get_queryset(self):
        try:
            self.post_user = User.objects.prefetch_related("posts").get(
                username__iexact=self.kwargs.get("username")
            )
        except User.DoesNotExist:
            raise Http404
        else:
            return self.post_user.posts.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["post_user"] = self.post_user
        return context


class PostDetail(LoginRequiredMixin, SelectRelatedMixin, generic.DetailView):
    model = models.Post
    select_related = ("user", "group")

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(
            user__username__iexact=self.kwargs.get("username")
        )


class CreatePost(LoginRequiredMixin, SelectRelatedMixin, generic.CreateView):
    #form_class = forms.PostForm
    fields = ('message','group')
    model = models.Post
    success_url = reverse_lazy("posts:all")

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user in post.groups.members.all:
            return True
        return False


class DeletePost(LoginRequiredMixin, SelectRelatedMixin, generic.DeleteView):
    model = models.Post
    select_related = ("user", "group")
    success_url = reverse_lazy("groups:all")

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user_id=self.request.user.id)

    def delete(self, *args, **kwargs):
        messages.success(self.request, "Post Deleted")
        return super().delete(*args, **kwargs)

blog/templates/blog/_paginator.html
  <!--Paginator -->
<div class="text-right">
  {% if is_paginated %}

    {% if page_obj.has_previous %}
      <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
      <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
    {% endif %}

    {% for num in page_obj.paginator.page_range %}
      {% if page_obj.number == num %}
        <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
      {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
        <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
      {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
      <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
      <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
    {% endif %}

  {% endif %}
</div>

blog/templates/blog/_post.html
<article class="media content-section">
  <img class="rounded-circle account-img" src="{{ post.author.profile.image.url }}" alt="">
  <div class="media-body">
    <div class="article-metadata">
      <a class="mr-2" href="{% url 'user-posts' post.author.username %}"></a>
      <a class="mr-2" href="{% url 'user-detail' post.author.profile.id %}">@{{ post.author }}</a><br>
      <small class="text-muted float">Posted: <a href="{% url 'post-detail' post.id %}">{{ post.date_posted|date:"d-M-y, h:i A" }}</a></small>

      {% if post.author == user or user.is_staff%}
        <div class="text-right">
          <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'post-update' post.id %}">Edit</a>
          <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'post-delete' post.id %}">Delete</a>
        </div>
      {% endif %}

    </div>
    <h4><a href="{% url 'post-detail' post.id %}">{{ post.title }}</a></h4>
    <p class="article-content">{{ post.content }}</p>
    <small class="text-muted float-right">Last Updated: {{ post.date_updated|date:"d-M-y, h:i A" }}</small>

  </div>

</article>

blog/templates/blog/_sidebar.html
{% if user.is_authenticated %}
<div class="container col-md-10">
  <div class="content-section">
    <h3 class="text-center text-info">Hello!</h3>
    <p class='text-muted text-center'>Welcome to NSU Social
      <ul class="list-group">

        <a href="{% url 'blog-home' %} "class="list-group-item list-group-item-action flex-column align-items-start bg-secondary text-center">
          <b class="mb-0 text-white">Latest Posts</b></a>

        <a href="{% url 'user-posts' user.username %}"class="list-group-item list-group-item-action flex-column align-items-start bg-secondary text-center">
          <b class="mb-0 text-white">Your Posts</b></a>

        <a href="{% url 'groups:all' %}"class="list-group-item list-group-item-action flex-column align-items-start bg-secondary text-center">
          <b class="mb-0 text-white">Groups</b></a>

        <a href="{% url 'members' %}"class="list-group-item list-group-item-action flex-column align-items-start bg-secondary text-center">
          <b class="mb-0 text-white">Community</b></a>

        <a href="{% url 'post-create' %}"class="list-group-item list-group-item-action flex-column align-items-start bg-info text-center">
          <b class="mb-0 text-white">New Post</b></a>

      </ul>
    </p>
  </div>
</div>
{% endif %}

blog/templates/blog/about.html
{% extends "blog/base.html" %}

{% block content %}
<div class="container col-md-10">
  <article class="media content-section">
    <div class="media-body">
      <div class="article-metadata">
        <h1>About</h1>
      </div>
      <br>
      <em><h5>Welcome to NSU Social</h5>
        A social networking site exclusively for the students of North South University.
        <br>
        You must be a student of NSU to be eligible to create an account here or see any of the content of this site.

      </em>
      <br>
      <br>
      <br>
      <strong>Developed by:</strong><br>
      <em>
        S. M. Al Faruqui [ID: 172 1395 042] <br>
        Subrena Islam [ID: 162 0283 042] <br>

      </em>
      <small>For CSE299-Spring-2019 (Sec-19)</small>
    </div>
  </article>
</div>
{% endblock content %}

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut icon" href="{% static 'blog/icon.png' %}" />
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'blog/main.css' %}">

  <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>


    {% if title %}
        <title>NSU Social - {{ title }}</title>
    {% else %}
        <title>NSU Social</title>
    {% endif %}
</head>

<body>

<header class="site-header">
  <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
    <div class="container-fluid">
      <a class="navbar-brand mr-4" href="{% url 'blog-home' %}">
        <img src="{% static 'blog/icon.png' %}" height="33px">  NSU Social</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarToggle">
        <div class="navbar-nav mr-auto">
          <a class="nav-item nav-link" href="{% url 'blog-home' %}">Home</a>

          {% if user.is_authenticated %}
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                Blog
              </a>
              <div class="dropdown-menu">


                <a class="dropdown-item " href="{% url 'blog-home' %}">All Post</a>
                <a class="dropdown-item border-bottom mb-2" href="{% url 'user-posts' user.username %}">Your Posts</a>
                <a class="dropdown-item " href="{% url 'post-create' %}">New Post</a>
              </div>
            </li>


            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="{% url 'groups:all' %}" id="navbardrop" data-toggle="dropdown">
                Groups
              </a>
              <div class="dropdown-menu">
                <a class="dropdown-item border-bottom mb-2" href="{% url 'groups:all' %}">All Groups</a>
                <a class="dropdown-item " href="{% url 'posts:all' %}">All Posts</a>
                <a class="dropdown-item border-bottom mb-2" href="{% url 'posts:for_user' username=user.username %}">Your Posts</a>

                <a class="dropdown-item " href="{% url 'posts:create' %}">Create Post</a>
                <a class="dropdown-item " href="{% url 'groups:create' %}">Create Group</a>

              </div>
            </li>

            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                Community
              </a>
              <div class="dropdown-menu">

                <a class="dropdown-item " href="{% url 'members' %}">Members</a>
                <a class="dropdown-item border-bottom mb-2" href="{% url 'students' %}">Students</a>
                <a class="dropdown-item " href="{% url 'add-student' %}">Add Student</a>
              </div>
            </li>
          {% endif %}



          <a class="nav-item nav-link" href="{% url 'blog-about' %}">About</a>



        </div>
        <!-- Navbar Right Side -->
        <div class="navbar-nav">

          {% if user.is_authenticated %}
            <a class="nav-item nav-link" href="{% url 'profile' %}"></a>
            <a class="nav-item nav-link" href="{% url 'post-create' %}">New Post</a>

            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                <img src="{{ user.profile.image.url }}" height="33px">
              </a>
              <div class="dropdown-menu dropdown-menu-right">

                <a class="dropdown-item " href="{% url 'profile' %}">Your Profile</a>
                <a class="dropdown-item " href="{% url 'user-posts' user.username %}">Your Posts</a>
                <a class="dropdown-item border-bottom mb-2" href="{% url 'editprofile' %}">Edit Profile</a>
                <a class="dropdown-item " href="{% url 'logout' %}">Logout</a>
              </div>
            </li>

          {% else %}
            <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
            <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
          {% endif %}
        </div>
      </div>
    </div>
  </nav>
</header>

    <main role="main" class="container-fluid">

      <div class="row">
        <div class=" col-md-2">
          <div class="container">
            <!-- Profile card -->
            {% if user.is_authenticated %}
              <div class="card">
                <img class="card-img-top" src="{{ user.profile.image.url }}" alt="Card image cap">
                <div class="card-body">
                  <h5 class="card-title text-uppercase text-center"><a href="{% url 'user-detail' user.profile.id %}">{{ user.username }}</a></h5>


                  <small>Blog Posts: <a href="{% url 'user-posts' user.username %}">{{ user.post.count }}</a></small><br>
                  <small>Group Posts: <a href="{% url 'posts:for_user' username=user.username %}">{{ user.posts.count }}</a></small><br>
                  <small>Joined: {{ user.profile.date_registered|date:"d M, Y"  }}</small><br>
                  <b class="text-info text-center">{{user.profile.status}}</b>
                  <br>

                  <!-- Social media links -->
                  <div class="container">
                    <a href="{{ user.profile.fb_link }}">
                      <img src="{% static 'logo/fblogo.png' %}" height="20px"  alt="">
                    </a>
                    <a href="{{ user.profile.twitter_link }}">
                      <img src="{% static 'logo/twitter.jpg' %}" height="20px"  alt="">
                    </a>
                    <a href="{{ user.profile.insta_link }}">
                      <img src="{% static 'logo/insta.png' %}" height="20px"  alt="">
                    </a>
                    <a href="{{ user.profile.git_link }}">
                      <img src="{% static 'logo/git.png' %}" height="20px"  alt="">
                    </a>
                    <a href="{{ user.profile.linkedin_link }}">
                      <img src="{% static 'logo/linkedin.png' %}" height="20px"  alt="">
                    </a>
                  </div>

                </div class="container">
                <a href="{% url 'editprofile' %}" class="btn btn-secondary mb-1">Edit Profile</a>
                <a href="{% url 'post-create' %}" class="btn btn-primary">New Post</a>
              </div>
            {% endif %}

          </div>
        </div>

        <div class="col-md-7">
          <div class="container">
            {% if messages %}
              {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
            {% block content %}{% endblock %}
          </div>

        </div>

        <div class="col-md-3">

          {% include "blog/_sidebar.html" %}
          {% block side_content %}{% endblock %}

        </div>
      </div>
    </main>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>


    <footer class="footer" style = "margin-top: 5rem;">
       <div class="container-flow jumbotron">
         <div class="row">

           <div class="col-md-12 col-lg-4">
             <div class="footer-logo">

               <a class="navbar-brand" href="{% url 'blog-home' %}"><b>NSU Social</b></a>
               <p>A social platform for the students of NSU.</p>

             </div>
           </div>

           <div class="col-sm-6 col-md-3 col-lg-2">
             <div class="list-menu">

               <h4>About Us</h4>

               <ul class="list-unstyled">
                 <li><a href="{% url 'blog-about' %}">About us</a></li>
               </ul>

             </div>
           </div>

           <div class="col-sm-6 col-md-3 col-lg-2">
             <div class="list-menu">

               <h4>Backend</h4>

               <ul class="list-unstyled">
                 <li><a href="#">Python</a></li>
                 <li><a href="#">Django</a></li>
               </ul>

             </div>
           </div>

           <div class="col-sm-6 col-md-3 col-lg-2">
             <div class="list-menu">

               <h4>Developed By</h4>

               <ul class="list-unstyled">
                 <li>Name: <a href="{% url 'user-detail' 10 %}">S. M. Al Faruqui</a></li>
                 <li>ID: <a href="#">172 1395 042</a></li>
               </ul>

             </div>
           </div>

           <div class="col-sm-6 col-md-3 col-lg-2">
             <div class="list-menu">

               <h4>Developed For</h4>

               <ul class="list-unstyled">
                 <li>Course: <a href="#">CSE 299</a></li>
                 <li>Sec: <a href="#">19</a></li>
                 <li>Semester: <a href="#">Sping, 2019</a></li>
                 <li>Faculty: <a href="#">ZBZ</a></li>
               </ul>

             </div>
           </div>

         </div>
       </div>

       <div class="copyrights">
         <div class="container text-center">
           <p>&copy; Copyrights NSU Social. All rights reserved.</p>
           <div class="credits">
           </div>
         </div>
       </div>

     </footer>
</body>
</html>

blog/templates/blog/home.html
{% extends "blog/base.html" %}
{% block content %}
<div class="container col-md-10">
  {% include "blog/_paginator.html" %}
    {% for post in posts %}
      {% include "blog/_post.html" %}
    {% endfor %}

    <!--Paginator -->
    {% include "blog/_paginator.html" %}
</div>
{% endblock content %}

blog/templates/blog/index.html
{% extends "blog/base.html" %}

{% block content %}
  <div class="container-flow">

  </div>
{% endblock content %}

{% block side_content %}
<div class="container">
  <div class="content-section">
    <h3>Hello!</h3>
    <p class='text-muted'>Welcome to NSU Soical
      <ul class="list-group">

        <a href="{% url 'blog-home' %} "class="list-group-item list-group-item-action flex-column align-items-start">
          <b class="mb-0" style = "color:#8308e0;">Latest Posts</b></a>

        <a href="{% url 'groups:all' %}"class="list-group-item list-group-item-action flex-column align-items-start">
          <b class="mb-0" style = "color:#8308e0;">Groups</b></a>

        <a href="{% url 'members' %}"class="list-group-item list-group-item-action flex-column align-items-start">
          <b class="mb-0" style = "color:#8308e0;">Community</b></a>

        <a href="{% url 'post-create' %}"class="list-group-item list-group-item-action flex-column align-items-start">
          <b class="mb-0" style = "color:#0aafc9;">New Post</b></a>

      </ul>
    </p>
  </div>
{% endblock %}

blog/templates/blog/newsfeed.html
{% extends "blog/base.html" %}
{% block content %}

{% if user.is_authenticated %}
  <h3>number: {{ num }}</h3>
  <h2>{{ user.username }}'s Newsfeed:</h2>

    {% for post in posts %}

        <article class="media content-section">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="#">{{ post.author }}</a>
              <small class="text-muted">{{ post.date_posted|date:"d M, Y" }}</small>
            </div>
            <h2><a class="article-title" href="#">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
          </div>
        </article>

    {% endfor %}
{% else %}
  <h2>Login to see your news feed</h2>
{% endif %}
{% endblock content %}

blog/templates/blog/post_confirm_delete.html
{% extends "blog/base.html" %}


{% block content %}
<div class="container col-md-10">
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete Post</legend>
                <h4>Are you sure you want to delete the post: <a href="{% url 'post-detail' object.id %}">{{ object.title }}</a></h4>
                  {% include "blog/_post.html" %}

            </fieldset>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">Confirm Delete</button>
                <a class="btn btn-outline-secondary" href="{% url 'post-detail' object.id %}">Go Back</a>
            </div>
        </form>
    </div>
  </div>
{% endblock content %}

blog/templates/blog/post_detail.html
{% extends "blog/base.html" %}
{% block content %}
<div class="container col-md-10">
  {% include "blog/_post.html" %}
</div>


{% endblock content %}

blog/templates/blog/post_form.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container col-md-10">
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Blog Post</legend>
                {{ form | crispy }}
            </fieldset>
            <div class="form-group text-center">
                <button class="btn btn-outline-info" type="submit">Post</button>
            </div>
        </form>
    </div>
</div>
{% endblock content %}

blog/templates/blog/user_posts.html
{% extends "blog/base.html" %}
{% block content %}
<div class="container col-md-10">
<h3 class="mb-3">Blog Posts by {{ view.kwargs.username }} ({{ page_obj.paginator.count }})</h3>
{% include "blog/_paginator.html" %}
  {% for post in posts %}
    {% include "blog/_post.html" %}
  {% endfor %}
{% include "blog/_paginator.html" %}
</div>
{% endblock content %}