blog/urls.py
from django.urls import path
from .views import (
    PostListView,
    PostDetailView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView,
    UserPostListView,
)
from . import views

urlpatterns = [
    path('index/', views.index, name = 'index'),
    path('', PostListView.as_view(), name = 'blog-home'),
    path('user/<str:username>', UserPostListView.as_view(), name = 'user-posts'),
    path('post/<int:pk>/', PostDetailView.as_view(), name = 'post-detail'), #url pattern with variable
    path('post/new/', PostCreateView.as_view(), name = 'post-create'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name = 'post-update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name = 'post-delete'),
    path('about/', views.about, name = 'blog-about'),
    path('newsfeed/', views.newsfeed, name = 'blog-newsfeed'),
]

#blog/post_list.html
#<app>/<model>_<viewtype>.html

posts/urls.py
from django.urls import path
from . import views

app_name='posts'

urlpatterns = [
    path('', views.PostList.as_view(), name="all"),
    path("new/", views.CreatePost.as_view(), name="create"),
    path("by/<username>/",views.UserPosts.as_view(),name="for_user"),
    path("by/<username>/<int:pk>/",views.PostDetail.as_view(),name="single"),
    path("delete/<int:pk>/",views.DeletePost.as_view(),name="delete"),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from users import views as user_views

from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('', include('users.urls')),
    path('groups/',include("groups.urls", namespace="groups")),
    path('posts/', include("posts.urls", namespace="posts")),

    path('register/', user_views.register, name = "register"),
    path('profile/', user_views.profile, name = "profile"),
    path('editprofile/', user_views.editprofile, name = "editprofile"),
    #path('members/', user_views.members, name = "members"),
    path('login/', auth_views.LoginView.as_view(template_name = 'users/login.html'), name = "login"),
    path('logout/', auth_views.LogoutView.as_view(template_name = 'users/logout.html'), name = "logout"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import UserListView, UserDetailView, StudentListView, CreateStudent, DeleteAccount
from . import views

urlpatterns = [
    path('members/', UserListView.as_view(), name = 'members'),
    path('students/', StudentListView.as_view(), name = 'students'),
    path('students/<int:pk>/update/', views.UpdateStudent.as_view(), name = 'student-update'),
    path("addstudent/", views.CreateStudent.as_view(), name="add-student"),

    path('members/<int:pk>/', UserDetailView.as_view(), name = 'user-detail'),
    path('user/<int:pk>/delete/', DeleteAccount.as_view(), name = 'user-delete'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from PIL import Image

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    nsu_id = models.IntegerField(null = True)
    image = models.ImageField(default='profile_pics/default.jpg', upload_to='profile_pics')
    status = models.CharField(max_length = 100, default = 'Status')
    bio = models.TextField(default = 'Bio')
    date_registered = models.DateTimeField(default=timezone.now)
    fb_link = models.URLField(default = 'https://www.facebook.com/')
    insta_link = models.URLField(default = 'https://www.instagram.com/')
    git_link = models.URLField(default = 'https://github.com/')
    linkedin_link = models.URLField(default = 'https://bd.linkedin.com/')
    twitter_link = models.URLField(default = 'https://twitter.com/')

    def __str__(self):
        return f'{self.user.username} Profile'

    def get_absolute_url(self):
        return reverse('user-detail', kwargs={'pk': self.pk})

class Student(models.Model):
    name = models.CharField(max_length = 50)
    id = models.IntegerField(primary_key=True)
    email = models.EmailField(unique = True)
    date_registered = models.DateTimeField(default=timezone.now)

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import get_object_or_404
from .models import Profile, Student

class UserRegisterForm(UserCreationForm):
    #email = forms.EmailField()
    email = forms.EmailField(label = (u'NSU Email Adress')) #for labelling
    #nsu_id = forms.IntegerField(label = (u'NSU ID'))
    #nsu_ID = forms.IntegerField(required=False)

    def clean_email(self):
        data = self.cleaned_data['email']
        if "@northsouth.edu" not in data:   # any check you need
            raise forms.ValidationError("Must be an official northsouth email address")
        return data


    # def clean(self):
    #     cleaned_data = super().clean()
    #     mail = cleaned_data.get('email')
    #     nsuID = cleaned_data.get('nsu_id')
    #     x = "afsaf"
    #     if Student.objects.filter(email = mail).count() > 0:
    #         x = get_object_or_404(Student, email=mail).id
    #     if x != nsuID:
    #         raise forms.ValidationError("ID and email don't match")
    #
    # def clean_email(self):
    #     data = self.cleaned_data['email']
    #     std = Student.objects.filter(email = data)
    #     if Student.objects.filter(email = data).count() == 0:
    #         raise forms.ValidationError("Must be an official NorthSouth email address")
    #     return data
    #
    # def clean_nsu_id(self):
    #     data = self.cleaned_data['nsu_id']
    #     std = Student.objects.filter(email = data)
    #     if Student.objects.filter(id = data).count() == 0:
    #         raise forms.ValidationError("Must be a valid id")
    #     return data

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()
    def clean_email(self):
        data = self.cleaned_data['email']
        if "@northsouth.edu" not in data:   # any check you need
            raise forms.ValidationError("Must be an official northsouth email address")
        return data

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email']

class ProfileUpdateForm(forms.ModelForm):
    # def clean_nsu_id(self):
    #     data = self.cleaned_data['nsu_id']
    #     if Student.objects.filter(id = data).count() == 0:
    #         raise forms.ValidationError("Must be an official NSU student ID")
    #     return data

    def clean_fb_link(self):
        data = self.cleaned_data['fb_link']
        if "facebook.com/" not in data:   # any check you need
            raise forms.ValidationError("Must be your facebook profile link")
        return data

    class Meta:
        model = Profile
        fields = [
            'nsu_id',
            'status',
            'image',
            'bio',
            'fb_link',
            'insta_link',
            'git_link',
            'linkedin_link',
            'twitter_link',
        ]

users/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView
)
from .forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm
from django.contrib.auth.models import User
from blog.models import Post
from groups.models import Group, GroupMember
from .models import Profile, Student
from django.urls import reverse_lazy

from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin

# Create your views here.
def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            #username = form.cleaned_data.get('username')
            messages.success(request, f'Account Creation Successful! You can login now')
            return redirect('login')
    else:
        form = UserRegisterForm()

    return render(request, 'users/register.html', {'form': form, 'title':'Registration',})

@login_required
def profile(request):
    context = {
        'posts' : Post.objects.all(),
        'groups' : Group.objects.all(),
        'title' : 'Profile',
    }
    return render(request, 'users/profile.html', context)



@login_required
def editprofile(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)

        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f'Account Update Successful!')
            return redirect('profile')
    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        'posts' : Post.objects.all(),
        'title' : 'Edit Profile',
        'u_form' : u_form,
        'p_form' : p_form,
    }

    return render(request, 'users/editprofile.html', context)

@login_required
def members(request):
    context = {
        'profiles' : User.objects.all(),
        #'posts' : Post.objects.all(),
        'title' : 'Members',

        #Project.objects.values('informationunit__username').distinct().count()
    }
    return render(request, 'users/members.html', context)


class UserListView(LoginRequiredMixin, ListView):
    model = Profile
    #template_name = 'user/members.html'
    #<app>/<model>_<viewtype>.html
    context_object_name = 'profiles' #use post.author instead of object.author
    ordering = ['user']
    paginate_by = 10 #buit in paginator function

class StudentListView(LoginRequiredMixin, ListView):
    model = Student
    context_object_name = 'students'
    template_name = 'users/students.html'
    ordering = ['id']
    paginate_by = 25

class CreateStudent(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    #form_class = forms.PostForm
    fields = ('name','id', 'email')
    model = Student
    success_url = reverse_lazy("students")

    def test_func(self):
        return self.request.user.is_staff

class UpdateStudent(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    fields = ['name','id', 'email']
    model = Student
    success_url = reverse_lazy("students")

    def form_valid(self, form):
            #form<this form> <set author> = current logged in user
            #form.instance.author = self.request.user
            #run overridden form_valid method
            return super().form_valid(form)

    def test_func(self):
        if self.request.user.is_staff:
            return True
        return False

    def update(self, *args, **kwargs):
        messages.success(self.request, "Student details Updated!")
        return super().update(*args, **kwargs)


class UserDetailView(LoginRequiredMixin, DetailView):
    model = Profile

class DeleteAccount(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = User
    success_url = reverse_lazy("members")
    template_name = 'users/user_confirm_delete.html'

    def test_func(self):
        return self.request.user.is_staff

    def delete(self, *args, **kwargs):
        messages.success(self.request, "User account Deleted from database")
        return super().delete(*args, **kwargs)

users/templates/users/editprofile.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container col-md-10">
    <div class="content-section">
      <div class="media">
        <img class="rounded-circle account-img" src="{{ user.profile.image.url }}">
        <div class="media-body">
          <h2 class="account-heading">{{ user.username }} </h2>
          <small>{{ user.email }}</small>

        </div>
        <a class="btn btn-info btn-sm mt-1 mb-1" href="{% url 'profile' %}">Profile</a>

      </div>
      <!-- FORM HERE -->
      <!-- enchtype saves images -->
      <form method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          <fieldset class="form-group">
              <legend class="border-bottom mb-4">Your Profile: </legend>
              {{ u_form | crispy }}
              {{ p_form | crispy }}
          </fieldset>
          <div class="form-group text-center">
              <button class="btn btn-outline-info" type="submit">Save</button>
          </div>
      </form>

    </div>
    </div>
{% endblock content %}

users/templates/users/login.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}

{% block content %}

<div class="container col-md-5" style = "margin-top: 8rem; margin-bottom: 5rem;">
    <div class="content-section bg-steel">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4 text-center text-info"><b>Sign In</b></legend>
                {{ form | crispy }}
            </fieldset>
            <div class="form-group text-center">
                <button class="btn btn-info" type="submit">Sign In</button>
            </div>
        </form>
        <div class="border-top pt-3 text-right">
            <small class="text-muted">
                Need to create a new account? <a class="ml-2" href="{% url 'register' %}">Register Here</a>
            </small>
        </div>
    </div>
</div>

{% endblock content %}

users/templates/users/logout.html
{% extends "blog/base.html" %}

{% block content %}
<div class="container col-md-8" style = "margin-top: 8rem; margin-bottom: 15rem;">
  <div class="content-section">
    <h2 class="border-bottom mb-4 text-info text-center">You have succefully logged out</h2>
    <div class="text-right">
      <small class="text-muted text-left">
          Login with a different account? <a class="ml-2" href="{% url 'login' %}">Sign In</a>
      </small>
    </div>

      </div>
  </div>
{% endblock content %}

users/templates/users/profile.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container col-md-10">
    <div class="content-section">
      <!-- Profile info HERE -->
      <div class="media">
        <img class="rounded-circle account-img" src="{{ user.profile.image.url }}">
        <div class="media-body">
          <a class="btn btn-info btn-sm mt-1 mb-1 float-right" href="{% url 'editprofile' %}">Edit Profile</a>
          <h2 class="account-heading">{{ user.username }} </h2>

          <p class="text-secondary">
            Name: {{ user.first_name }} {{ user.last_name }} <br>
            Email: {{ user.email }} <br>
            Memeber Since: {{ user.profile.date_registered|date:"d M, Y"  }}<br>
          </p>

          <p class="text-info">{{ user.profile.status }}</p>
          <br>
          <a class="btn btn-primary" href="{% url 'user-posts' user.username %}">See Blog posts <span class="badge badge-light">
  					{{ user.post.count }}</span></a>
          <a class="btn btn-info" href="{% url 'posts:for_user' username=user.username %}">See Group posts <span class="badge badge-light">
  					{{ user.posts.count }}</span></a>
          <br>
        </div>


      </div>

      <legend class="border-bottom mb-4">Bio: </legend>
      <article class="media content-section">
        <p>{{ user.profile.bio }}</p>
      </article>

      <!-- Groups HERE -->
        <legend class="border-bottom mb-4">Groups: </legend>
        <div class="col-md-12">
        	<div class="list-group">
        		{% for group in groups %}
            {% if user in group.members.all %}
        		<a href="{% url 'groups:single' slug=group.slug %}"
        		class="list-group-item list-group-item-action flex-column align-items-start">
        			<h3 class="mb-1">{{ group.name }}</h3>
        			<p class="mb-1">{{ group.description_html|safe }}</p>
        			<div class="d-flex w-40 justify-content-between">
        				<small class="text-muted"><span class="badge badge-secondary">
        					{{ group.members.count }}</span> member{{ group.members.count|pluralize }}</small>
        				<small class="text-muted"><span class="badge badge-secondary">
        					{{ group.posts.count }}</span> post{{ group.posts.count|pluralize }}</small>
        			<span></span><span></span>
        			</div>
        		</a>
            {% endif %}
        		{% endfor %}
        	</div>
        </div>
    </div>
</div>
{% endblock content %}

users/templates/users/profile_detail.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
<div class="container col-md-10">

    <div class="content-section">
      <!-- Profile info HERE -->
      <div class="media">
        <img class="rounded-circle account-img" src="{{ object.image.url }}">
        <div class="media-body">
          <h2 class="account-heading">{{ object.user.username }} </h2>

          <p class="text-info">{{ object.status }}</p>

          <table class="container">
            <tr>
              <td>Name</td>
              <td>: {{ object.user.first_name }} {{ object.user.last_name }}</td>
            </tr>
            <tr>
              <td>Email</td>
              <td>: {{ object.user.email }}</td>
            </tr>
            <tr>
              <td>Joined</td>
              <td>: {{object.date_registered | date:"M d, Y"}}</td>
            </tr>
          </table>
          <br>
          <a class="btn btn-primary" href="{% url 'user-posts' object.user.username %}">See Blog posts <span class="badge badge-light">
  					{{ object.user.post.count }}</span></a>
          <a class="btn btn-info" href="{% url 'posts:for_user' username=object.user.username %}">See Group posts <span class="badge badge-light">
  					{{ object.user.posts.count }}</span></a>
          <br>
          <br>
          <!-- Social media links -->
          <div class="container">
            <a href="{{ object.fb_link }}">
              <img src="{% static 'logo/fblogo.png' %}" height="20px"  alt="">
            </a>
            <a href="{{ object.twitter_link }}">
              <img src="{% static 'logo/twitter.jpg' %}" height="20px"  alt="">
            </a>
            <a href="{{ object.insta_link }}">
              <img src="{% static 'logo/insta.png' %}" height="20px"  alt="">
            </a>
            <a href="{{ object.git_link }}">
              <img src="{% static 'logo/git.png' %}" height="20px"  alt="">
            </a>
            <a href="{{ object.linkedin_link }}">
              <img src="{% static 'logo/linkedin.png' %}" height="20px"  alt="">
            </a>
          </div>
          <br>



        </div>
      </div>

      <legend class="border-bottom mb-4 text-info">Bio</legend>
      <article class="media content-section">
        <p>{{ object.bio }}</p>

      </article>
      <legend class="border-bottom mb-4 text-info text-center">Posts</legend>
      {% for post in object.user.post.all reversed %}
        {% include "blog/_post.html" %}
      {% endfor %}

      <!-- Posts HERE -->

    </div>
  </div>
{% endblock content %}

users/templates/users/profile_list.html
{% extends "blog/base.html" %}
{% block content %}
<div class="container col-md-10">
  <legend class="border-bottom mb-4">All Members ( {{ page_obj.paginator.count }} ) : </legend>

  <!--Paginator -->
{% include "blog/_paginator.html" %}

    {% for p in profiles %}
        <article class="media content-section">
          <img class="rounded-circle account-img" src="{{ p.image.url }}" alt="">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{% url 'user-detail' p.id %}">{{ p.user.username }} </a>

              <small class="text-muted"><a href="{% url 'user-detail' p.id %}">
                ({{ p.user.email }})</a></small>
                <small class="float-right">Member Since: {{ p.date_registered|date:"d M, Y"  }}</small>
            </div>
            <p class="text-info">{{ p.status }}</p>
            <small>Blog Posts: <a href="{% url 'user-posts' p.user.username %}">{{ p.user.post.count }}</a></small><br>
            <small>Group Posts: <a href="{% url 'posts:for_user' username=p.user.username %}">{{ p.user.posts.count }}</a></small><br>

            {% if user.is_staff %}
              <a class="btn btn-danger btn-sm mt-1 mb-1 float-right" href="{% url 'user-delete' p.user.id %}">Delete User</a>
            {% endif %}
          </div>

        </article>
    {% endfor %}
    {% include "blog/_paginator.html" %}
  </div>
{% endblock content %}

users/templates/users/register.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container col-md-7">
  <div class="content-section">
      <form method="POST">
          {% csrf_token %}
          <fieldset class="form-group">
              <legend class="border-bottom mb-4 text-center text-info">Account Registration</legend>
              {{ form | crispy }}
          </fieldset>
          <div class="form-group text-center">
              <button class="btn btn-outline-info" type="submit">Sign Up</button>
          </div>
      </form>
      <div class="border-top pt-3 mb-5 text-right">
          <small class="text-muted">
              Already Have An Account? <a class="ml-2" href="{% url 'login' %}">Sign In</a>
          </small>
      </div>
  </div>
</div>

{% endblock content %}

users/templates/users/student_form.html
{% extends "posts/post_base.html" %}
{% load crispy_forms_tags %}

{% block post_content %}
<div class="container col-md-10">
	<div class="content-section">
			<form method="POST">
					{% csrf_token %}
					<fieldset class="form-group">
							<legend class="border-bottom mb-4">Add new student</legend>
							{{ form | crispy }}
					</fieldset>
					<div class="form-group">
							<button class="btn btn-outline-info" type="submit">Add</button>
					</div>
			</form>
	</div>
</div>
{% endblock %}

users/templates/users/students.html
{% extends "blog/base.html" %}
{% block content %}
<div class="container col-md-10">
  <legend class="border-bottom mb-4">All Students( {{page_obj.paginator.count }} ): </legend>


  <!--Paginator -->
{% include "blog/_paginator.html" %}
  <table class="table table-hover table-bordered table-striped">
    <thead>
      <tr class="table-primary">
        <th>Id</th>
        <th>Name</th>
        <th>Email Address</th>
      </tr>
    </thead>

    <tbody>
      {% for p in students %}
      <tr>
        <td>{{p.id}}</td>
        <td>{{p.name}}</td>
        <td>{{p.email}}</td>
      </tr>
      {% endfor %}
    </tbody>

  </table>

  <!--Paginator -->
{% include "blog/_paginator.html" %}
</div>
{% endblock content %}

users/templates/users/user_confirm_delete.html
{% extends "blog/base.html" %}


{% block content %}
<div class="container col-md-10">
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete User</legend>
                <h4>Are you sure you want to delete the user: {{ object.username }}</h4>
                <b class="text-danger">Be careful! this is cannot be undone.</b>

            </fieldset>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">Delete</button>
                <a class="btn btn-outline-secondary" href="{% url 'members' %}">Go Back</a>
            </div>
        </form>
    </div>
  </div>
{% endblock content %}