blog/urls.py
from django.urls import path
from .views import (
    PostListView,
    PostDetailView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView,
    UserPostListView,
)
from . import views

urlpatterns = [
    path('index/', views.index, name = 'index'),
    path('', PostListView.as_view(), name = 'blog-home'),
    path('user/<str:username>', UserPostListView.as_view(), name = 'user-posts'),
    path('post/<int:pk>/', PostDetailView.as_view(), name = 'post-detail'), #url pattern with variable
    path('post/new/', PostCreateView.as_view(), name = 'post-create'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name = 'post-update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name = 'post-delete'),
    path('about/', views.about, name = 'blog-about'),
    path('newsfeed/', views.newsfeed, name = 'blog-newsfeed'),
]

#blog/post_list.html
#<app>/<model>_<viewtype>.html

posts/urls.py
from django.urls import path
from . import views

app_name='posts'

urlpatterns = [
    path('', views.PostList.as_view(), name="all"),
    path("new/", views.CreatePost.as_view(), name="create"),
    path("by/<username>/",views.UserPosts.as_view(),name="for_user"),
    path("by/<username>/<int:pk>/",views.PostDetail.as_view(),name="single"),
    path("delete/<int:pk>/",views.DeletePost.as_view(),name="delete"),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from users import views as user_views

from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('', include('users.urls')),
    path('groups/',include("groups.urls", namespace="groups")),
    path('posts/', include("posts.urls", namespace="posts")),

    path('register/', user_views.register, name = "register"),
    path('profile/', user_views.profile, name = "profile"),
    path('editprofile/', user_views.editprofile, name = "editprofile"),
    #path('members/', user_views.members, name = "members"),
    path('login/', auth_views.LoginView.as_view(template_name = 'users/login.html'), name = "login"),
    path('logout/', auth_views.LogoutView.as_view(template_name = 'users/logout.html'), name = "logout"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse

# pip install misaka
#import misaka

from groups.models import Group

from django.contrib.auth import get_user_model
User = get_user_model()


class Post(models.Model):
    user = models.ForeignKey(User, related_name="posts",on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now=True)
    message = models.TextField()
    message_html = models.TextField(editable=False)
    group = models.ForeignKey(Group, related_name="posts",null=True, blank=True,on_delete=models.CASCADE)

    def __str__(self):
        return self.message

    def save(self, *args, **kwargs):
        #self.message_html = misaka.html(self.message)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse(
            "posts:single",
            kwargs={
                "username": self.user.username,
                "pk": self.pk
            }
        )

    class Meta:
        ordering = ["-created_at"]
        unique_together = ["user", "message"]

posts/forms.py
from django import forms
from . import models
from groups.models import Group, GroupMember
from django.contrib.auth.models import User


class PostForm(forms.ModelForm):
    class Meta:
        fields = ("group", "message")
        model = models.Post

    def clean(self):
        cleaned_data = super().clean()
        grp_name = cleaned_data.get('group')

        if Group.objects.filter(members = User).count() == 0:
            raise forms.ValidationError("You are not in this group")

posts/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.urls import reverse_lazy
from django.http import Http404
from django.views import generic

# pip install django-braces
from braces.views import SelectRelatedMixin

from . import forms
from . import models

from django.contrib.auth import get_user_model
User = get_user_model()


class PostList(LoginRequiredMixin, SelectRelatedMixin, generic.ListView):
    model = models.Post
    select_related = ("user", "group")
    paginate_by = 10


class UserPosts(LoginRequiredMixin, generic.ListView):
    model = models.Post
    template_name = "posts/user_post_list.html"
    paginate_by = 10

    def get_queryset(self):
        try:
            self.post_user = User.objects.prefetch_related("posts").get(
                username__iexact=self.kwargs.get("username")
            )
        except User.DoesNotExist:
            raise Http404
        else:
            return self.post_user.posts.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["post_user"] = self.post_user
        return context


class PostDetail(LoginRequiredMixin, SelectRelatedMixin, generic.DetailView):
    model = models.Post
    select_related = ("user", "group")

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(
            user__username__iexact=self.kwargs.get("username")
        )


class CreatePost(LoginRequiredMixin, SelectRelatedMixin, generic.CreateView):
    #form_class = forms.PostForm
    fields = ('message','group')
    model = models.Post
    success_url = reverse_lazy("posts:all")

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user in post.groups.members.all:
            return True
        return False


class DeletePost(LoginRequiredMixin, SelectRelatedMixin, generic.DeleteView):
    model = models.Post
    select_related = ("user", "group")
    success_url = reverse_lazy("groups:all")

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user_id=self.request.user.id)

    def delete(self, *args, **kwargs):
        messages.success(self.request, "Post Deleted")
        return super().delete(*args, **kwargs)

posts/templates/posts/_post.html
<div class="container-fluid">


  <article class="media content-section">
    <img class="rounded-circle account-img" src="{{ post.user.profile.image.url }}" alt="">
    <div class="media-body">
      <div class="article-metadata">
        <a class="mr-2" href="{% url 'user-detail' post.user.profile.id %}">@{{ post.user.username }}</a>
        <small class="text-muted"><a href="{% url 'posts:single' username=post.user.username pk=post.pk %}">
          {{ post.created_at|date:"d-M-y, h:i A" }}</a></small>
        
          {% if post.group %}
			<span class="group-name">in <a href="{% url 'groups:single' slug=post.group.slug %}">{{ post.group.name }}</a></span>
			{% endif %}



      </div>
      <p class="article-content">{{ post.message }}</p>
    </div>
    {% if post.user == user %}
      <div class="">
        <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'posts:delete' pk=post.pk %}" title="delete" ">Delete</a>
      </div>
    {% endif %}
  </article>
</div>

posts/templates/posts/post_base.html
{% extends "blog/base.html" %}

{% block content %}
<div class="posts-page">
	<div class="container">
		{% block prepost %}{% endblock %}
		{% block post_content %}{% endblock %}
		{% block post_post %}{% endblock %}
	</div>
</div>
{% endblock %}

{% block side_content %}
  {% block group_side %}{% endblock %}
{% endblock %}

posts/templates/posts/post_confirm_delete.html
{% extends "posts/post_base.html" %}

{% block post_content %}
<div class="container col-md-10">
	<h3>Are you sure you want to delete this post?</h3>

	<div class="posts">
		{% include "posts/_post.html" with post=object hide_delete=True %}
	</div>

	<form method="POST">
		{% csrf_token %}
		<input type="submit" value="Confirm Delete" class="btn btn-danger btn-large">
		<a href="{% url 'posts:single' username=user.username pk=object.pk %}" class="btn btn-outline-secondary">Go Back</a>
	</form>
</div>
{% endblock %}

posts/templates/posts/post_detail.html
{% extends "posts/post_base.html" %}

{% block post_content %}
<div class="container col-md-10">
    {% include "posts/_post.html" %}
 </div>
{% endblock %}

posts/templates/posts/post_form.html
{% extends "posts/post_base.html" %}
{% load crispy_forms_tags %}

{% block post_content %}
<div class="container col-md-10">
	<div class="content-section">
			<form method="POST">
					{% csrf_token %}
					<fieldset class="form-group">
							<legend class="border-bottom mb-4">New Group Post</legend>
							{{ form | crispy }}
					</fieldset>
					<div class="form-group">
							<button class="btn btn-outline-info" type="submit">Post</button>
					</div>
			</form>
	</div>
</div>
{% endblock %}

posts/templates/posts/post_list.html
{% extends "posts/post_base.html" %}


{% block post_content %}
<div class="container col-md-10">
	{% for post in post_list %}
  {% include "posts/_post.html" %}
	{% endfor %}
</div>

<!--Paginator -->
{% if is_paginated %}

	{% if page_obj.has_previous %}
		<a class="btn btn-outline-info mb-4" href="?page=1">First</a>
		<a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
	{% endif %}

	{% for num in page_obj.paginator.page_range %}
		{% if page_obj.number == num %}
			<a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
		{% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
			<a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
		{% endif %}
	{% endfor %}

	{% if page_obj.has_next %}
		<a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
		<a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
	{% endif %}

{% endif %}
{% endblock %}


{% block group_side %}

{% endblock %}

posts/templates/posts/user_post_list.html
{% extends "posts/post_base.html" %}

{% block post_content %}
<div class="container col-md-10">
<h3 class="mb-3">Group Posts by {{ post_user.username }} ({{ post_user.posts.count }})</h3>
{% include "blog/_paginator.html" %}
	{% for post in post_list %}
		{% include "posts/_post.html" %}
	{% endfor %}
{% include "blog/_paginator.html" %}
</div>
<!--Paginator -->
{% endblock %}